// <auto-generated />
using AspCoreZoo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspCoreZoo.Migrations
{
    [DbContext(typeof(ZooContext))]
    partial class ZooContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspCoreZoo.Model.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Energy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Animal");
                });

            modelBuilder.Entity("AspCoreZoo.Model.Elephant", b =>
                {
                    b.HasBaseType("AspCoreZoo.Model.Animal");

                    b.HasDiscriminator().HasValue("Elephant");
                });

            modelBuilder.Entity("AspCoreZoo.Model.Lion", b =>
                {
                    b.HasBaseType("AspCoreZoo.Model.Animal");

                    b.HasDiscriminator().HasValue("Lion");
                });

            modelBuilder.Entity("AspCoreZoo.Model.Monkey", b =>
                {
                    b.HasBaseType("AspCoreZoo.Model.Animal");

                    b.HasDiscriminator().HasValue("Monkey");
                });
#pragma warning restore 612, 618
        }
    }
}
